name: study_teach
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.0.0
  dots_indicator: ^3.0.0
  path_provider:
  camera: ^0.10.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  android: true
  background_image: assets/images/blue_bg.png
  image: assets/images/splash_icon_2.png
  android_12:
    image: assets/images/splash_icon.png
    color: "#0046FB"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
